import { CITIES, getCityName } from './cities';
export { getCityName };

export const VEHICLE_TYPES = [
  { id: 'mini-truck', label: 'Mini Truck', capacityRange: '1-3 Tons', icon: 'truck' },
  { id: 'pickup', label: 'Pickup', capacityRange: '1-2 Tons', icon: 'truck' },
  { id: 'tata-ace', label: 'Tata Ace', capacityRange: '0.75-1 Ton', icon: 'truck' },
  { id: 'medium-truck', label: 'Medium Truck', capacityRange: '5-10 Tons', icon: 'truck' },
  { id: 'heavy-truck', label: 'Heavy Truck', capacityRange: '10-25 Tons', icon: 'truck' },
  { id: 'trailer', label: 'Trailer / Container', capacityRange: '20-40 Tons', icon: 'truck' },
  { id: 'refrigerated', label: 'Refrigerated', capacityRange: '5-15 Tons', icon: 'truck' },
  { id: 'flatbed', label: 'Flatbed', capacityRange: '10-30 Tons', icon: 'truck' },
];

export const SHIPMENT_TYPES = [
  'General Goods',
  'Construction Material',
  'FMCG / Retail',
  'Agricultural Produce',
  'Industrial Equipment',
  'Electronics',
  'Perishable / Cold Chain',
  'Furniture',
  'Automotive Parts',
  'Textiles',
  'Hazardous Material',
  'Pharmaceuticals',
];

export const BUSINESS_TYPES = [
  'Manufacturing',
  'Retail / E-commerce',
  'Wholesale / Distribution',
  'Construction',
  'Agriculture',
  'FMCG',
  'Pharmaceuticals',
  'Automotive',
  'Electronics',
  'Textiles',
  'Logistics / 3PL',
  'Other',
];

// ─── Truckers ───────────────────────────────────────────────
export const TRUCKERS = [
  {
    id: 'trk-001',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@khaalinahi.in',
    phone: '+91 98765 43210',
    vehicleNumber: 'RJ14 CA 1234',
    vehicleType: 'heavy-truck',
    vehicleCapacity: 20,
    currentLocation: 'jaipur',
    preferredRoutes: ['jaipur-delhi', 'jaipur-agra', 'jaipur-ahmedabad'],
    reliabilityScore: 94,
    completedTrips: 287,
    cancelledTrips: 3,
    onTimeRate: 96,
    responseTime: '8 min',
    rating: 4.8,
  memberSince: '2023-01-15',
  status: 'available',
  capacityUtilization: 78,
    emptyKmAvoided: 1840,
    co2Saved: 642,
    earnings: 284500,
    returnTripEarnings: 89200,
  avatar: 'RK',
  bio: 'Experienced fleet operator covering North India corridors. Specializes in heavy haulage.',
  truckModel: 'Tata LPT 1613',
    rcValid: '2027-03-15',
    insuranceValid: '2026-08-20',
  permitType: 'National Permit',
  gpsEnabled: true,
  verified: true,
  documentsVerified: true,
  pan: 'ABCDE1234F',
  gst: '08ABCDE1234F1Z5',
  bankAccount: 'HDFC •••• 4521',
  upiId: 'rajesh@hdfcbank',
  address: 'Sikar Road, Jaipur, Rajasthan',
    emergencyContact: '+91 98765 11111 (Suresh Kumar)',
    preferredLanes: ['NH-48', 'NH-21', 'NH-8'],
    fuelEfficiency: '4.2 km/l',
    avgTripDuration: '18 hours',
    maxPayload: 20,
    dimensions: '7.5m × 2.4m × 2.6m',
    bodyType: 'Container',
    ownershipType: 'Owner-cum-Driver',
    fleetSize: 1,
    drivingLicense: 'RJ1420120001234',
    licenseValid: '2029-06-30',
  },
  {
    id: 'trk-002',
    name: 'Mohammed Irfan',
    email: 'irfan@khaalinahi.in',
    phone: '+91 98123 45678',
    vehicleNumber: 'DL1C AA 5678',
    vehicleType: 'medium-truck',
    vehicleCapacity: 10,
    currentLocation: 'delhi',
    preferredRoutes: ['delhi-mumbai', 'delhi-jaipur', 'delhi-kanpur'],
    reliabilityScore: 88,
    completedTrips: 156,
    cancelledTrips: 5,
    onTimeRate: 91,
    responseTime: '12 min',
    rating: 4.6,
    memberSince: '2023-06-20',
    status: 'on-trip',
    capacityUtilization: 65,
    emptyKmAvoided: 920,
    co2Saved: 318,
    earnings: 192000,
    returnTripEarnings: 58400,
    avatar: 'MI',
    bio: 'Mid-segment carrier focused on Delhi-Mumbai corridor. Reliable and punctual.',
    truckModel: 'Eicher Pro 3015',
    rcValid: '2026-11-10',
    insuranceValid: '2026-05-15',
    permitType: 'National Permit',
    gpsEnabled: true,
    verified: true,
    documentsVerified: true,
    pan: 'FGHIJ5678K',
    gst: '07FGHIJ5678K1Z2',
    bankAccount: 'SBI •••• 8832',
    upiId: 'irfan@oksbi',
    address: 'Okhla Phase 2, New Delhi',
    emergencyContact: '+91 98123 00000 (Aamir)',
    preferredLanes: ['NH-48', 'NH-19'],
    fuelEfficiency: '5.1 km/l',
    avgTripDuration: '24 hours',
    maxPayload: 10,
    dimensions: '6.2m × 2.2m × 2.4m',
    bodyType: 'Flatbed',
    ownershipType: 'Owner',
    fleetSize: 2,
    drivingLicense: 'DL0120140005678',
    licenseValid: '2028-12-31',
  },
  {
    id: 'trk-003',
    name: 'Suresh Patel',
    email: 'suresh.patel@khaalinahi.in',
    phone: '+91 99887 76655',
    vehicleNumber: 'GJ01 KL 9012',
    vehicleType: 'trailer',
    vehicleCapacity: 30,
    currentLocation: 'ahmedabad',
    preferredRoutes: ['ahmedabad-mumbai', 'ahmedabad-delhi', 'ahmedabad-jaipur'],
    reliabilityScore: 91,
    completedTrips: 203,
    cancelledTrips: 2,
    onTimeRate: 94,
    responseTime: '6 min',
    rating: 4.9,
    memberSince: '2022-11-05',
    status: 'available',
    capacityUtilization: 82,
    emptyKmAvoided: 2240,
    co2Saved: 780,
    earnings: 358000,
    returnTripEarnings: 124500,
    avatar: 'SP',
    bio: 'Long-haul trailer operator covering Western India. High reliability and GPS-enabled fleet.',
    truckModel: 'Ashok Leyland 3118',
    rcValid: '2027-08-22',
    insuranceValid: '2026-10-30',
    permitType: 'National Permit',
    gpsEnabled: true,
    verified: true,
    documentsVerified: true,
    pan: 'LMNOP9012Q',
    gst: '24LMNOP9012Q1Z8',
    bankAccount: 'ICICI •••• 1199',
    upiId: 'suresh@icici',
    address: 'Naroda GIDC, Ahmedabad, Gujarat',
    emergencyContact: '+91 99887 12345 (Kamlesh)',
    preferredLanes: ['NH-48', 'NE-1'],
    fuelEfficiency: '3.8 km/l',
    avgTripDuration: '30 hours',
    maxPayload: 30,
    dimensions: '9.5m × 2.5m × 2.8m',
    bodyType: 'Container',
    ownershipType: 'Fleet Owner',
    fleetSize: 4,
    drivingLicense: 'GJ0120150009012',
    licenseValid: '2030-04-15',
  },
  {
    id: 'trk-004',
    name: 'Amit Singh',
    email: 'amit.singh@khaalinahi.in',
    phone: '+91 97654 32109',
    vehicleNumber: 'UP16 AB 3456',
    vehicleType: 'refrigerated',
    vehicleCapacity: 12,
    currentLocation: 'kanpur',
    preferredRoutes: ['kanpur-delhi', 'kanpur-lucknow', 'kanpur-agra'],
    reliabilityScore: 86,
    completedTrips: 98,
    cancelledTrips: 4,
    onTimeRate: 89,
    responseTime: '15 min',
    rating: 4.5,
    memberSince: '2024-01-10',
    status: 'available',
    capacityUtilization: 58,
    emptyKmAvoided: 540,
    co2Saved: 188,
    earnings: 142000,
    returnTripEarnings: 41200,
    avatar: 'AS',
    bio: 'Cold-chain specialist. Pharmaceuticals and perishable goods expert.',
    truckModel: 'Tata Ultra 1518 Reefer',
    rcValid: '2027-02-28',
    insuranceValid: '2026-07-12',
    permitType: 'National Permit',
    gpsEnabled: true,
    verified: true,
    documentsVerified: true,
    pan: 'QRSTU3456V',
    gst: '09QRSTU3456V1Z3',
    bankAccount: 'BOB •••• 6677',
    upiId: 'amit@barodampay',
    address: 'Panki, Kanpur, Uttar Pradesh',
    emergencyContact: '+91 97654 99999 (Deepak)',
    preferredLanes: ['NH-19', 'NH-30'],
    fuelEfficiency: '4.5 km/l',
    avgTripDuration: '14 hours',
    maxPayload: 12,
    dimensions: '6.8m × 2.3m × 2.5m',
    bodyType: 'Refrigerated',
    ownershipType: 'Owner-cum-Driver',
    fleetSize: 1,
    drivingLicense: 'UP1620160003456',
    licenseValid: '2029-09-18',
  },
];

// ─── Shippers ────────────────────────────────────────────────
export const SHIPPERS = [
  {
    id: 'shp-001',
    name: 'Priya Sharma',
    email: 'priya.sharma@relianceretail.in',
    phone: '+91 90123 45678',
    companyName: 'Reliance Retail Logistics',
    businessType: 'Retail / E-commerce',
    commonPickups: ['mumbai', 'pune', 'ahmedabad'],
    commonDeliveries: ['delhi', 'jaipur', 'agra'],
    rating: 4.7,
    memberSince: '2023-03-12',
    activeShipments: 3,
    completedShipments: 142,
    totalSpent: 1840000,
    costSaved: 312000,
    avatar: 'PS',
    gst: '27AAACR5055K1Z5',
    address: 'Navi Mumbai, Maharashtra',
    verified: true,
    bio: 'Leading retail supply chain. High-volume shipper across Western-Northern corridors.',
  },
  {
    id: 'shp-002',
    name: 'Vikram Reddy',
    email: 'vikram@constructionplus.in',
    phone: '+91 93456 78901',
    companyName: 'Construction Plus Industries',
    businessType: 'Construction',
    commonPickups: ['ahmedabad', 'jaipur'],
    commonDeliveries: ['delhi', 'gurugram', 'noida'],
    rating: 4.5,
    memberSince: '2023-08-20',
    activeShipments: 2,
    completedShipments: 78,
    totalSpent: 920000,
    costSaved: 148000,
    avatar: 'VR',
    gst: '08AAACC1234K1Z9',
    address: 'Sitapura, Jaipur, Rajasthan',
    verified: true,
    bio: 'Construction material supplier. Regular heavy-load shipments to NCR.',
  },
  {
    id: 'shp-003',
    name: 'Anjali Mehta',
    email: 'anjali@freshfarmlogistics.in',
    phone: '+91 91234 56789',
    companyName: 'FreshFarm Cold Chain',
    businessType: 'Agriculture',
    commonPickups: ['pune', 'ahmedabad'],
    commonDeliveries: ['mumbai', 'delhi'],
    rating: 4.8,
    memberSince: '2024-02-01',
    activeShipments: 1,
    completedShipments: 56,
    totalSpent: 680000,
    costSaved: 92000,
    avatar: 'AM',
    gst: '27AAFFC7890K1Z2',
    address: 'Hadapsar, Pune, Maharashtra',
    verified: true,
    bio: 'Cold-chain agricultural produce. Requires refrigerated vehicles for perishable goods.',
  },
];

// ─── Shipments ───────────────────────────────────────────────
export const SHIPMENTS = [
  {
    id: 'shp-ord-001',
    shipperId: 'shp-001',
    shipperName: 'Reliance Retail Logistics',
    pickupLocation: 'mumbai',
    deliveryLocation: 'delhi',
    weight: 8,
    volume: 32,
    shipmentType: 'FMCG / Retail',
    requiredVehicleType: 'heavy-truck',
    pickupDateTime: '2026-08-16T18:30:00',
    deliveryDeadline: '2026-08-17T18:00:00',
    specialRequirements: 'Handle with care. Fragile packaging.',
    status: 'open',
    estimatedCost: 45000,
    distance: 1418,
    postedAt: '2026-08-15T10:00:00',
    priority: 'high',
    partialLoadEligible: true,
    insuranceRequired: true,
    fragile: true,
    temperatureControlled: false,
    declaredValue: 850000,
    packagingType: 'Palletized',
    numPackages: 48,
    pickupContact: 'Mumbai DC — +91 90123 11111',
    deliveryContact: 'Delhi Hub — +91 90123 22222',
  },
  {
    id: 'shp-ord-002',
    shipperId: 'shp-002',
    shipperName: 'Construction Plus Industries',
    pickupLocation: 'jaipur',
    deliveryLocation: 'gurugram',
    weight: 15,
    volume: 45,
    shipmentType: 'Construction Material',
    requiredVehicleType: 'heavy-truck',
    pickupDateTime: '2026-08-16T06:00:00',
    deliveryDeadline: '2026-08-16T20:00:00',
    specialRequirements: 'Tarpaulin cover required.',
    status: 'open',
    estimatedCost: 28000,
    distance: 235,
    postedAt: '2026-08-15T08:30:00',
    priority: 'medium',
    partialLoadEligible: false,
    insuranceRequired: false,
    fragile: false,
    temperatureControlled: false,
    declaredValue: 320000,
    packagingType: 'Bulk Bags',
    numPackages: 20,
    pickupContact: 'Sitapura Yard — +91 93456 11111',
    deliveryContact: 'Gurugram Site — +91 93456 22222',
  },
  {
    id: 'shp-ord-003',
    shipperId: 'shp-003',
    shipperName: 'FreshFarm Cold Chain',
    pickupLocation: 'pune',
    deliveryLocation: 'mumbai',
    weight: 6,
    volume: 24,
    shipmentType: 'Perishable / Cold Chain',
    requiredVehicleType: 'refrigerated',
    pickupDateTime: '2026-08-16T04:00:00',
    deliveryDeadline: '2026-08-16T10:00:00',
    specialRequirements: 'Temperature: 2-8°C. Pre-cooling required.',
    status: 'open',
    estimatedCost: 18500,
    distance: 148,
    postedAt: '2026-08-15T14:00:00',
    priority: 'high',
    partialLoadEligible: true,
    insuranceRequired: true,
    fragile: true,
    temperatureControlled: true,
    declaredValue: 450000,
    packagingType: 'Crates',
    numPackages: 120,
    pickupContact: 'Hadapsar Packhouse — +91 91234 11111',
    deliveryContact: 'Vashi Market — +91 91234 22222',
  },
  {
    id: 'shp-ord-004',
    shipperId: 'shp-001',
    shipperName: 'Reliance Retail Logistics',
    pickupLocation: 'ahmedabad',
    deliveryLocation: 'jaipur',
    weight: 4,
    volume: 18,
    shipmentType: 'Electronics',
    requiredVehicleType: 'medium-truck',
    pickupDateTime: '2026-08-17T10:00:00',
    deliveryDeadline: '2026-08-17T22:00:00',
    specialRequirements: 'Anti-static packaging. GPS tracking mandatory.',
    status: 'open',
    estimatedCost: 22000,
    distance: 676,
    postedAt: '2026-08-15T16:00:00',
    priority: 'medium',
    partialLoadEligible: true,
    insuranceRequired: true,
    fragile: true,
    temperatureControlled: false,
    declaredValue: 1200000,
    packagingType: 'Cartons',
    numPackages: 35,
    pickupContact: 'Ahmedabad DC — +91 90123 33333',
    deliveryContact: 'Jaipur Hub — +91 90123 44444',
  },
  {
    id: 'shp-ord-005',
    shipperId: 'shp-002',
    shipperName: 'Construction Plus Industries',
    pickupLocation: 'jaipur',
    deliveryLocation: 'delhi',
    weight: 3,
    volume: 12,
    shipmentType: 'Construction Material',
    requiredVehicleType: 'medium-truck',
    pickupDateTime: '2026-08-16T14:00:00',
    deliveryDeadline: '2026-08-16T22:00:00',
    specialRequirements: 'None',
    status: 'open',
    estimatedCost: 12000,
    distance: 281,
    postedAt: '2026-08-15T12:00:00',
    priority: 'low',
    partialLoadEligible: true,
    insuranceRequired: false,
    fragile: false,
    temperatureControlled: false,
    declaredValue: 180000,
    packagingType: 'Bags',
    numPackages: 60,
    pickupContact: 'Sitapura Yard — +91 93456 33333',
    deliveryContact: 'Delhi Site — +91 93456 44444',
  },
  {
    id: 'shp-ord-006',
    shipperId: 'shp-003',
    shipperName: 'FreshFarm Cold Chain',
    pickupLocation: 'ahmedabad',
    deliveryLocation: 'delhi',
    weight: 9,
    volume: 36,
    shipmentType: 'Perishable / Cold Chain',
    requiredVehicleType: 'refrigerated',
    pickupDateTime: '2026-08-18T05:00:00',
    deliveryDeadline: '2026-08-19T02:00:00',
    specialRequirements: 'Temperature: 0-4°C. Continuous temp logging.',
    status: 'unmatched',
    estimatedCost: 52000,
    distance: 925,
    postedAt: '2026-08-15T09:00:00',
    priority: 'high',
    partialLoadEligible: false,
    insuranceRequired: true,
    fragile: true,
    temperatureControlled: true,
    declaredValue: 680000,
    packagingType: 'Crates',
    numPackages: 90,
    pickupContact: 'Ahmedabad Packhouse — +91 91234 55555',
    deliveryContact: 'Azadpur Mandi — +91 91234 66666',
    unmatchedReasons: [
      'No refrigerated vehicles available on this route for the time window',
      'Pickup window is narrow (5:00 AM – 7:00 AM)',
      'Long-haul cold-chain capacity is currently limited',
    ],
    suggestedChanges: [
      { action: 'Extend pickup window by 2 hours', impact: '3 additional potential matches may become available' },
      { action: 'Allow split delivery at Vadodara hub', impact: '2 medium-capacity reefer trucks available' },
    ],
  },
];

// ─── Matches ─────────────────────────────────────────────────
export const MATCHES = [
  {
    id: 'mtch-001',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    truckerAvatar: 'RK',
    shipmentId: 'shp-ord-002',
    shipperName: 'Construction Plus Industries',
    route: { from: 'jaipur', to: 'gurugram' },
    matchScore: 96,
    capacity: 15,
    truckCapacity: 20,
    pickupTime: '2026-08-16T06:00:00',
    deliveryDeadline: '2026-08-16T20:00:00',
    estimatedEarnings: 28000,
    reliabilityScore: 94,
    distance: 235,
    reasons: [
      { label: 'Route aligned', passed: true, detail: 'Trucker preferred route Jaipur → Delhi NCR' },
      { label: 'Capacity available', passed: true, detail: '15T required, 20T available (75% utilization)' },
      { label: 'Time compatible', passed: true, detail: 'Pickup 6:00 AM fits trucker availability window' },
      { label: 'Vehicle compatible', passed: true, detail: 'Heavy truck required and available' },
      { label: 'Reliable carrier', passed: true, detail: '94/100 reliability, 96% on-time rate' },
    ],
    status: 'recommended',
    partialLoad: false,
    co2Saved: 82,
    emptyKmAvoided: 235,
    estimatedCost: 28000,
  },
  {
    id: 'mtch-002',
    truckerId: 'trk-003',
    truckerName: 'Suresh Patel',
    truckerAvatar: 'SP',
    shipmentId: 'shp-ord-001',
    shipperName: 'Reliance Retail Logistics',
    route: { from: 'mumbai', to: 'delhi' },
    matchScore: 92,
    capacity: 8,
    truckCapacity: 30,
    pickupTime: '2026-08-16T18:30:00',
    deliveryDeadline: '2026-08-17T18:00:00',
    estimatedEarnings: 45000,
    reliabilityScore: 91,
    distance: 1418,
    reasons: [
      { label: 'Route aligned', passed: true, detail: 'Ahmedabad-based, Mumbai → Delhi is preferred corridor' },
      { label: 'Capacity available', passed: true, detail: '8T required, 30T available (27% utilization — partial load)' },
      { label: 'Time compatible', passed: true, detail: 'Evening pickup aligns with delivery schedule' },
      { label: 'Vehicle compatible', passed: true, detail: 'Heavy truck available for long-haul' },
      { label: 'Reliable carrier', passed: true, detail: '91/100 reliability, 94% on-time rate' },
    ],
    status: 'recommended',
    partialLoad: true,
    co2Saved: 496,
    emptyKmAvoided: 1418,
    estimatedCost: 45000,
  },
  {
    id: 'mtch-003',
    trukerId: 'trk-001',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    truckerAvatar: 'RK',
    shipmentId: 'shp-ord-005',
    shipperName: 'Construction Plus Industries',
    route: { from: 'jaipur', to: 'delhi' },
    matchScore: 88,
    capacity: 3,
    truckCapacity: 20,
    pickupTime: '2026-08-16T14:00:00',
    deliveryDeadline: '2026-08-16T22:00:00',
    estimatedEarnings: 12000,
    reliabilityScore: 94,
    distance: 281,
    reasons: [
      { label: 'Route aligned', passed: true, detail: 'Jaipur → Delhi is a preferred route' },
      { label: 'Capacity available', passed: true, detail: '3T required, 20T available (15% utilization — partial load candidate)' },
      { label: 'Time compatible', passed: true, detail: 'Afternoon pickup fits schedule' },
      { label: 'Vehicle compatible', passed: true, detail: 'Medium/heavy truck both acceptable' },
      { label: 'Reliable carrier', passed: true, detail: '94/100 reliability score' },
    ],
    status: 'recommended',
    partialLoad: true,
    co2Saved: 98,
    emptyKmAvoided: 281,
    estimatedCost: 12000,
  },
  {
    id: 'mtch-004',
    truckerId: 'trk-004',
    truckerName: 'Amit Singh',
    truckerAvatar: 'AS',
    shipmentId: 'shp-ord-003',
    shipperName: 'FreshFarm Cold Chain',
    route: { from: 'pune', to: 'mumbai' },
    matchScore: 84,
    capacity: 6,
    truckCapacity: 12,
    pickupTime: '2026-08-16T04:00:00',
    deliveryDeadline: '2026-08-16T10:00:00',
    estimatedEarnings: 18500,
    reliabilityScore: 86,
    distance: 148,
    reasons: [
      { label: 'Route aligned', passed: false, detail: 'Trucker based in Kanpur — repositioning required (148 km)' },
      { label: 'Capacity available', passed: true, detail: '6T required, 12T available (50% utilization)' },
      { label: 'Time compatible', passed: true, detail: 'Early morning pickup — trucker available' },
      { label: 'Vehicle compatible', passed: true, detail: 'Refrigerated truck available — cold-chain ready' },
      { label: 'Reliable carrier', passed: true, detail: '86/100 reliability, 89% on-time rate' },
    ],
    status: 'recommended',
    partialLoad: false,
    co2Saved: 52,
    emptyKmAvoided: 148,
    estimatedCost: 18500,
  },
];

// ─── Trips ───────────────────────────────────────────────────
export const TRIPS = [
  {
    id: 'trip-001',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: 'Reliance Retail Logistics',
    route: { from: 'delhi', to: 'jaipur' },
    shipmentType: 'FMCG / Retail',
    weight: 12,
    capacity: 20,
    date: '2026-08-14',
    status: 'completed',
    earnings: 32000,
    emptyKmAvoided: 281,
    co2Saved: 98,
    matchScore: 95,
    distance: 281,
    pickupTime: '06:00',
    deliveryTime: '11:30',
    loadedReturn: true,
    notes: 'On-time delivery. Shipper rated 5 stars.',
  },
  {
    id: 'trip-002',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: 'Construction Plus Industries',
    route: { from: 'jaipur', to: 'agra' },
    shipmentType: 'Construction Material',
    weight: 8,
    capacity: 20,
    date: '2026-08-10',
    status: 'completed',
    earnings: 14500,
    emptyKmAvoided: 231,
    co2Saved: 81,
    matchScore: 91,
    distance: 231,
    pickupTime: '08:00',
    deliveryTime: '13:00',
    loadedReturn: true,
    notes: 'Smooth delivery. Partial load (40% utilization).',
  },
  {
    id: 'trip-003',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: 'Reliance Retail Logistics',
    route: { from: 'agra', to: 'delhi' },
    shipmentType: 'Electronics',
    weight: 5,
    capacity: 20,
    date: '2026-08-16',
    status: 'upcoming',
    earnings: 8500,
    emptyKmAvoided: 231,
    co2Saved: 81,
    matchScore: 89,
    distance: 231,
    pickupTime: '14:00',
    deliveryTime: '18:00',
    loadedReturn: true,
    notes: 'Match confirmed. Pickup scheduled.',
  },
  {
    id: 'trip-004',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: 'FreshFarm Cold Chain',
    route: { from: 'delhi', to: 'kanpur' },
    shipmentType: 'Agricultural Produce',
    weight: 10,
    capacity: 20,
    date: '2026-08-18',
    status: 'upcoming',
    earnings: 22000,
    emptyKmAvoided: 480,
    co2Saved: 168,
    matchScore: 93,
    distance: 480,
    pickupTime: '05:00',
    deliveryTime: '16:00',
    loadedReturn: true,
    notes: 'Return trip matched. High-value shipment.',
  },
  {
    id: 'trip-005',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: 'Reliance Retail Logistics',
    route: { from: 'delhi', to: 'jaipur' },
    shipmentType: 'General Goods',
    weight: 6,
    capacity: 20,
    date: '2026-08-05',
    status: 'completed',
    earnings: 18000,
    emptyKmAvoided: 0,
    co2Saved: 0,
    matchScore: 0,
    distance: 281,
    pickupTime: '09:00',
    deliveryTime: '14:30',
    loadedReturn: false,
    notes: 'Empty return — no match found. This is the problem PratiGati solves.',
  },
  {
    id: 'trip-006',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: 'Construction Plus Industries',
    route: { from: 'jaipur', to: 'ahmedabad' },
    shipmentType: 'Construction Material',
    weight: 15,
    capacity: 20,
    date: '2026-08-01',
    status: 'completed',
    earnings: 26000,
    emptyKmAvoided: 676,
    co2Saved: 237,
    matchScore: 90,
    distance: 676,
    pickupTime: '07:00',
    deliveryTime: '20:00',
    loadedReturn: true,
    notes: 'Long-haul return match. Excellent utilization.',
  },
  {
    id: 'trip-007',
    truckerId: 'trk-001',
    truckerName: 'Rajesh Kumar',
    shipperName: '—',
    route: { from: 'delhi', to: 'lucknow' },
    shipmentType: '—',
    weight: 0,
    capacity: 20,
    date: '2026-07-28',
    status: 'cancelled',
    earnings: 0,
    emptyKmAvoided: 0,
    co2Saved: 0,
    matchScore: 0,
    distance: 557,
    pickupTime: '—',
    deliveryTime: '—',
    loadedReturn: false,
    notes: 'Shipper cancelled due to weather. Auto-rematch initiated.',
  },
];

// ─── Predictions ─────────────────────────────────────────────
export const PREDICTIONS = [
  {
    id: 'pred-001',
    route: { from: 'delhi', to: 'jaipur' },
    date: '2026-08-16',
    timeWindow: '17:00 – 21:00',
    predictedCapacity: 42,
    confidence: 82,
    demandLevel: 'high',
    historicalTrips: 34,
    avgEmptyRate: 68,
    notes: 'High empty-return corridor. 68% of trucks return empty historically.',
    matchOpportunities: 12,
  },
  {
    id: 'pred-002',
    route: { from: 'mumbai', to: 'ahmedabad' },
    date: '2026-08-16',
    timeWindow: '14:00 – 20:00',
    predictedCapacity: 52,
    confidence: 87,
    demandLevel: 'high',
    historicalTrips: 41,
    avgEmptyRate: 54,
    notes: 'Strong industrial demand. 12 active shipments awaiting capacity.',
    matchOpportunities: 15,
  },
  {
    id: 'pred-003',
    route: { from: 'delhi', to: 'mumbai' },
    date: '2026-08-17',
    timeWindow: '08:00 – 14:00',
    predictedCapacity: 68,
    confidence: 79,
    demandLevel: 'high',
    historicalTrips: 28,
    avgEmptyRate: 61,
    notes: 'Long-haul corridor. High capacity but also high demand.',
    matchOpportunities: 9,
  },
  {
    id: 'pred-004',
    route: { from: 'jaipur', to: 'ahmedabad' },
    date: '2026-08-16',
    timeWindow: '10:00 – 16:00',
    predictedCapacity: 31,
    confidence: 74,
    demandLevel: 'medium',
    historicalTrips: 22,
    avgEmptyRate: 58,
    notes: 'Medium-demand corridor. Construction material flow.',
    matchOpportunities: 6,
  },
  {
    id: 'pred-005',
    route: { from: 'kanpur', to: 'delhi' },
    date: '2026-08-17',
    timeWindow: '06:00 – 12:00',
    predictedCapacity: 29,
    confidence: 71,
    demandLevel: 'medium',
    historicalTrips: 18,
    avgEmptyRate: 63,
    notes: 'Industrial goods flow. Morning departure pattern.',
    matchOpportunities: 5,
  },
  {
    id: 'pred-006',
    route: { from: 'pune', to: 'mumbai' },
    date: '2026-08-16',
    timeWindow: '04:00 – 08:00',
    predictedCapacity: 38,
    confidence: 85,
    demandLevel: 'high',
    historicalTrips: 52,
    avgEmptyRate: 42,
    notes: 'Short-haul high-frequency corridor. Cold-chain demand in mornings.',
    matchOpportunities: 18,
  },
];

// ─── Notifications ───────────────────────────────────────────
export const NOTIFICATIONS = [
  {
    id: 'ntf-001',
    type: 'match',
    title: 'New match recommendation',
    message: '96% match found: Jaipur → Gurugram, ₹28,000',
    timestamp: '2 min ago',
    read: false,
    priority: 'high',
  },
  {
    id: 'ntf-002',
    type: 'prediction',
    title: 'Capacity prediction alert',
    message: '42T empty capacity predicted on Delhi → Jaipur tomorrow 5-9 PM',
    timestamp: '15 min ago',
    read: false,
    priority: 'medium',
  },
  {
    id: 'ntf-003',
    type: 'shipment',
    title: 'New shipment request',
    message: 'Reliance Retail posted a shipment: Mumbai → Delhi, 8T',
    timestamp: '1 hour ago',
    read: false,
    priority: 'medium',
  },
  {
    id: 'ntf-004',
    type: 'trip',
    title: 'Trip completed',
    message: 'Trip #trip-001 completed. ₹32,000 earned, 281 empty km avoided.',
    timestamp: '3 hours ago',
    read: true,
    priority: 'low',
  },
  {
    id: 'ntf-005',
    type: 'alert',
    title: 'Better match found',
    message: 'A 92% match is now available for your Mumbai → Delhi return trip.',
    timestamp: '5 hours ago',
    read: true,
    priority: 'high',
  },
  {
    id: 'ntf-006',
    type: 'deadline',
    title: 'Delivery deadline approaching',
    message: 'Trip #trip-003 pickup at 2:00 PM today. Ensure truck is ready.',
    timestamp: '6 hours ago',
    read: true,
    priority: 'high',
  },
];

// ─── Impact Metrics ──────────────────────────────────────────
export const IMPACT_METRICS = {
  totalEmptyKmAvoided: 1840,
  totalFuelSaved: 438,
  totalCostSaved: 318000,
  totalCo2Saved: 642,
  totalRevenue: 284500,
  capacityUtilization: 78,
  successfulMatches: 142,
  partialLoadMatches: 38,
  totalTrips: 287,
  loadedReturns: 204,
  emptyReturns: 83,
  avgMatchScore: 89,
};

export const WEEKLY_EARNINGS = [
  { week: 'Week 1', earnings: 42000, returnEarnings: 12000, emptyKm: 280 },
  { week: 'Week 2', earnings: 38000, returnEarnings: 18500, emptyKm: 140 },
  { week: 'Week 3', earnings: 52000, returnEarnings: 28000, emptyKm: 0 },
  { week: 'Week 4', earnings: 48000, returnEarnings: 22400, emptyKm: 95 },
  { week: 'Week 5', earnings: 56000, returnEarnings: 31000, emptyKm: 0 },
  { week: 'Week 6', earnings: 49000, returnEarnings: 26000, emptyKm: 50 },
];

export const MONTHLY_IMPACT = [
  { month: 'Mar', emptyKm: 820, co2: 286, cost: 142000 },
  { month: 'Apr', emptyKm: 940, co2: 328, cost: 168000 },
  { month: 'May', emptyKm: 1120, co2: 392, cost: 198000 },
  { month: 'Jun', emptyKm: 1380, co2: 483, cost: 234000 },
  { month: 'Jul', emptyKm: 1560, co2: 546, cost: 268000 },
  { month: 'Aug', emptyKm: 1840, co2: 642, cost: 318000 },
];

export const CORRIDOR_ANALYTICS = [
  { corridor: 'Delhi → Jaipur', demand: 92, capacity: 42, matches: 28, emptyRate: 68 },
  { corridor: 'Mumbai → Delhi', demand: 88, capacity: 68, matches: 22, emptyRate: 61 },
  { corridor: 'Mumbai → Ahmedabad', demand: 85, capacity: 52, matches: 31, emptyRate: 54 },
  { corridor: 'Delhi → Agra', demand: 72, capacity: 28, matches: 18, emptyRate: 55 },
  { corridor: 'Jaipur → Ahmedabad', demand: 68, capacity: 31, matches: 14, emptyRate: 58 },
  { corridor: 'Kanpur → Delhi', demand: 65, capacity: 29, matches: 12, emptyRate: 63 },
  { corridor: 'Pune → Mumbai', demand: 90, capacity: 38, matches: 35, emptyRate: 42 },
  { corridor: 'Ahmedabad → Mumbai', demand: 82, capacity: 52, matches: 26, emptyRate: 48 },
];

// ─── Admin Platform Data ─────────────────────────────────────
export const ADMIN_STATS = {
  totalUsers: 1284,
  totalTruckers: 842,
  totalShippers: 442,
  activeTrucks: 318,
  activeShipments: 156,
  successfulMatches: 1248,
  pendingMatches: 34,
  unmatchedShipments: 18,
  totalEmptyKmAvoided: 184200,
  totalCostSaved: 31200000,
  totalCo2Saved: 64200,
  platformRevenue: 4200000,
  avgMatchScore: 87,
  avgCapacityUtilization: 74,
  activeCorridors: 24,
};

export const ADMIN_WEEKLY = [
  { week: 'W1', matches: 42, shipments: 58, trucks: 280 },
  { week: 'W2', matches: 51, shipments: 64, trucks: 295 },
  { week: 'W3', matches: 48, shipments: 61, trucks: 310 },
  { week: 'W4', matches: 63, shipments: 72, trucks: 318 },
];

// ─── Helper Functions ─────────────────────────────────────────
export function getMatchesForTrucker(truckerId) {
  return MATCHES.filter((m) => m.truckerId === truckerId);
}

export function getMatchesForShipper(shipperId) {
  return MATCHES.filter((m) => m.shipperId === shipperId || m.shipperName?.includes('Reliance') || m.shipperName?.includes('Construction') || m.shipperName?.includes('FreshFarm'));
}

export function getTripsForTrucker(truckerId) {
  return TRIPS.filter((t) => t.truckerId === truckerId);
}

export function getTruckerById(id) {
  return TRUCKERS.find((t) => t.id === id);
}

export function getShipperById(id) {
  return SHIPPERS.find((s) => s.id === id);
}

export function getVehicleTypeLabel(typeId) {
  return VEHICLE_TYPES.find((v) => v.id === typeId)?.label || typeId;
}

export function getVehicleTypeCapacity(typeId) {
  return VEHICLE_TYPES.find((v) => v.id === typeId)?.capacityRange || '';
}

export function formatCurrency(amount) {
  const { formatCurrencyGlobal } = require('@/lib/i18n');
  return formatCurrencyGlobal(amount);
}

export function formatDateTime(isoString) {
  if (!isoString || isoString === '—') return '—';
  const d = new Date(isoString);
  return d.toLocaleString('en-IN', {
    day: 'numeric',
    month: 'short',
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

export function formatTime(isoString) {
  if (!isoString || isoString === '—') return '—';
  const d = new Date(isoString);
  return d.toLocaleString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: true,
  });
}

export function formatDate(dateStr) {
  if (!dateStr || dateStr === '—') return '—';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
}
